### ISSUE TITLE
no binaryen method succeeded. consider enabling more options

### ISSUE THREAD

**Issue by x4niko** [nmrugg/stockfish.js#19]
when require() stockfish.js as a module, i got exception:

../StockfishSample/node_modules/stockfish/src/stockfish.js:4
 */var STOCKFISH=(function(){function load_stockfish(console,WasmPath){if(typeof navigator!=="undefined"&&(/MSIE|Trident|Edge/i.test(navigator.userAgent)||/Safari/i.test(navigator.userAgent)&&!/Chrome|CriOS/i.test(navigator.userAgent))){var dateNow=Date.now}var Module={wasmBinaryFile:WasmPath};if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRON
abort("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods") at Error
    at jsStackTrace (/Users/niko/workspace/NodejsProjects/StockfishSample/node_modules/stockfish/src/stockfish.js:4:18295)
    at stackTrace (/Users/niko/workspace/NodejsProjects/StockfishSample/node_modules/stockfish/src/stockfish.js:4:18466)
    at abort (/Users/niko/workspace/NodejsProjects/StockfishSample/node_modules/stockfish/src/stockfish.js:4:87197)
    at Object.asm (/Users/niko/workspace/NodejsProjects/StockfishSample/node_modules/stockfish/src/stockfish.js:4:30931)
    at load_stockfish (/Users/niko/workspace/NodejsProjects/StockfishSample/node_modules/stockfish/src/stockfish.js:4:78362)
    at Immediate._onImmediate (/Users/niko/workspace/NodejsProjects/StockfishSample/node_modules/stockfish/src/stockfish.js:4:91682)
    at processImmediate (internal/timers.js:445:19)

my code below:
`
var Stockfish = require('stockfish');
stockfishes[sid] = Stockfish();

stockfishes[sid].onmessage = function onmessage(event) {
    console.log('onmessage = ' + event.data);
};

stockfishes[sid].postMessage('uci');
`

**Comment by GSTVAC** [comment]
Same problem here. @x4niko were you able to fix this?

**Comment by nmrugg** [comment]
The path to the WASM binary needed to be passed in manually. That's no longer required in v10.0.1 (see 5be93562606dba334ba656623229f41b12b9d333).
