### ISSUE TITLE
Run server.js corrrectly

### ISSUE THREAD

**Issue by regodo** [nmrugg/stockfish.js#73]
Hi guys.

I am trying to run example/server.js file.

When I open the site with Chrome I got this error in the console:
```
stockfish.js:41 Uncaught RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 2e 2e 2f 73 @+0). Build with -s ASSERTIONS=1 for more info.
    at B (stockfish.js:41:337)
    at stockfish.js:99:293
```

I installed the emsdk app.

I tried to run the build.js file also but it has a problem too:
```
Error: ENOENT: no such file or directory, open 'F:\Git\immortal_game_bot\stockfish.js-master\src\stockfish.worker.js'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (F:\Git\immortal_game_bot\stockfish.js-master\build.js:399:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'F:\\Git\\immortal_game_bot\\stockfish.js-master\\src\\stockfish.worker.js'
}
```

I am on Windows.

What I am doing wrong?

**Comment by erjoalgo** [comment]
See https://github.com/nmrugg/stockfish.js/issues/102. I had success by symlinking `stockfish.worker.js` to one of the options, like `stockfish-16.1.js`.
